export const TOP_OVERLAY_FALLBACK_HEIGHT = 332;
export const HEADER_TOP_HEIGHT = 52;
export const HEADER_VERTICAL_PADDING = 12;
export const FIXED_HEADER_HEIGHT =
  HEADER_TOP_HEIGHT + HEADER_VERTICAL_PADDING * 2;
export const HEADER_HORIZONTAL_PADDING = 20;
export const SCREEN_FADE_THRESHOLD = 0.3;
